[build]
  command = "npm run build"
  publish = "dist" # Change this to match your actual build output directory
  functions = "dist/netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions.scheduler]
  schedule = "0 */12 * * *"  # 每6小时运行一次

[functions]
  included_files = ["node_modules/puppeteer/**/*"]
  node_bundler = "esbuild"

[functions.api]
  timeout = 60
[dev]
  port = 8888  # 指定你想要的端口